# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 02:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updatedate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
