# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='question',
            name='updatedate',
            field=models.CharField(max_length=255),
        ),
    ]
