# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0002_auto_20160925_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
