# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0004_userpersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonal',
            name='area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userpersonal',
            name='sex',
            field=models.NullBooleanField(),
        ),
    ]
